import pandas as pd
import numpy as np
import sys
import os

# Allow import from backend root
sys.path.append("/Users/eduardbelskih/.gemini/antigravity/scratch/statproject/backend")

from app.modules.data_prep import DataPrepEngine

def main():
    engine = DataPrepEngine()
    
    print("--- Test 1: PII Sanitization ---")
    df_pii = pd.DataFrame({
        "ID": [1, 2],
        "FIO_Patient": ["Ivanov I.I.", "Petrov P.P."],
        "Data_Rozhdeniya": ["01.01.1980", "05.05.1990"],
        "Hb_Level": [120, 130]
    })
    clean_df, sanitized = engine.sanitize_dataset(df_pii)
    print("Original Columns:", df_pii.columns.tolist())
    print("Sanitized Columns:", sanitized)
    print("Clean Data:\n", clean_df)
    
    if clean_df["FIO_Patient"].iloc[0] == "********" and "Data_Rozhdeniya" in sanitized:
        print("✅ PII Sanitization Passed")
    else:
        print("❌ PII Sanitization Failed")
        
    print("\n--- Test 2: Header Detection ---")
    # Simulate messy excel
    data = [
        [np.nan, np.nan, np.nan],
        ["Report generated by machine", np.nan, np.nan],
        [np.nan, np.nan, np.nan],
        ["Group", "Time_1", "Time_2"], # Real header
        ["A", 10, 20],
        ["B", 15, 25]
    ]
    df_messy = pd.DataFrame(data)
    header_idx = engine.detect_header(df_messy)
    print(f"Detected Header Row Index: {header_idx}")
    
    if header_idx == 3:
        print("✅ Header Detection Passed")
    else:
        print(f"❌ Header Detection Failed (Expected 3, got {header_idx})")

    print("\n--- Test 3: Structure Analysis (Wide to Long) ---")
    df_wide = pd.DataFrame({
        "Group": ["A", "B"],
        "Hb_T1": [120, 110],
        "Hb_T2": [125, 115],
        "Hb_T3": [130, 120],
        "Age": [30, 40]
    })
    suggestion = engine.analyze_structure(df_wide)
    print("Suggestion:", suggestion)
    
    if suggestion["type"] == "wide" and "Hb" in suggestion["melt_candidates"][0]["prefix"]:
        print("✅ Structure Analysis Passed")
    else:
        print("❌ Structure Analysis Failed")

if __name__ == "__main__":
    main()
