"""
R Executor - runs R scripts securely via Rscript.
"""
import subprocess
import tempfile
import os
import json
import logging
import shutil
from typing import Dict, Any, Tuple

logger = logging.getLogger(__name__)

class RExecutor:
    """Executes R code for statistical analysis."""
    
    def __init__(self):
        self.rscript_path = self._find_rscript()

    def _find_rscript(self) -> str:
        """Find Rscript binary."""
        paths = [
            "/usr/bin/Rscript",
            "/usr/local/bin/Rscript",
            "/opt/homebrew/bin/Rscript", # macOS Apple Silicon
            "Rscript" # PATH
        ]
        for p in paths:
            if shutil.which(p): # Check if executable
                return p
            if os.path.exists(p) and os.access(p, os.X_OK):
                return p
        
        # Fallback to just "Rscript" hoping it's in PATH
        return "Rscript"

    async def execute_code(self, code: str, dataset_path: str, context: Dict[str, Any] = None) -> Tuple[str, str]:
        """
        Run R code in a temporary directory.
        Returns: (output_log, errors)
        """
        import shutil
        
        # Security check: Basic keyword blocklist
        blacklist = ["system(", "shell(", "file.remove", "unlink"]
        for bad in blacklist:
            if bad in code:
                raise ValueError(f"Security violation: Forbidden R function '{bad}' detected.")

        with tempfile.TemporaryDirectory() as tmp_dir:
            # 1. Prepare Environment
            script_path = os.path.join(tmp_dir, "script.R")
            
            # Inject data loading helper
            # We assume the code generated by LLM respects the prompt and uses 'dataset_path' variable if we inject it,
            # OR we prepend a variable definition.
            # The prompt says: "DATASET PATH: {dataset_path}" is provided in prompt, 
            # so the LLM should write code that uses this path. 
            # However, to be safe, we can enforce the variable:
            
            # Escape backslashes for R string
            safe_dataset_path = dataset_path.replace("\\", "/")
            preamble = f'dataset_path <- "{safe_dataset_path}"\nsetwd("{tmp_dir}")\n'
            
            full_code = preamble + code
            
            with open(script_path, "w") as f:
                f.write(full_code)

            # 2. Execute Rscript
            cmd = [self.rscript_path, script_path]
            
            try:
                process = subprocess.run(
                    cmd,
                    capture_output=True,
                    text=True,
                    timeout=300 # 5 minutes max
                )
                
                stdout = process.stdout
                stderr = process.stderr
                
                # Check for R errors (Rscript exit code is non-zero on error)
                if process.returncode != 0:
                     return stdout, f"R Execution Error (Exit Code {process.returncode}):\n{stderr}"

                # 3. Collect Artifacts (Plots, JSON results)
                # The LLM prompt instructs to save plots to 'plots_dir' or current dir.
                # We need to capture files created in tmp_dir and move them to a persistent location?
                # For now, let's assume the LLM writes JSON output to stdout or a specific file.
                # Ideally, we should parse the output or look for a results.json file.
                
                # If the prompt asks to print JSON to stdout:
                # We return stdout.
                
                return stdout, stderr

            except subprocess.TimeoutExpired:
                return "", "R Execution timed out (300s limit)."
            except Exception as e:
                return "", f"System Error executing R: {e}"
