import time
import os
import json
import shutil
import random

# Configuration
TASKS_DIR = "workspace/tasks"
INCOMING = f"{TASKS_DIR}/incoming"
PROCESSING = f"{TASKS_DIR}/processing"
COMPLETED = f"{TASKS_DIR}/completed"
FAILED = f"{TASKS_DIR}/failed"

def get_glm_response(prompt):
    """
    Placeholder for actual GLM API call. 
    In the future, request the GLM API Key from env and use requests.post()
    """
    print(f"[LLM] Generating code for: {prompt[:50]}...")
    time.sleep(2) # Simulate work
    return f"# Generated by Roo Code (GLM)\n# Task: {prompt}\n\ndef implemented_feature():\n    pass"

def process_file(filename):
    src = f"{INCOMING}/{filename}"
    processing_path = f"{PROCESSING}/{filename}"
    
    print(f"[*] Picking up task: {filename}")
    
    # 1. Move to Processing
    try:
        shutil.move(src, processing_path)
    except FileNotFoundError:
        return # Already grabbed by another worker
        
    try:
        # 2. Read Task
        with open(processing_path, "r") as f:
            task = json.load(f)
            
        description = task.get("description", "")
        print(f"[*] Executing: {description}")
        
        # 3. "Execute" (Call LLM)
        code_result = get_glm_response(description)
        
        # 4. Save Result (Mocking file creation)
        task["result"] = code_result
        task["status"] = "completed"
        task["completed_at"] = time.time()
        
        # 5. Move to Completed
        dest = f"{COMPLETED}/{filename}"
        with open(processing_path, "w") as f:
            json.dump(task, f, indent=2)
            
        shutil.move(processing_path, dest)
        print(f"[+] Task {filename} completed successfully.")
        
    except Exception as e:
        print(f"[-] Error: {e}")
        # Move to Failed
        shutil.move(processing_path, f"{FAILED}/{filename}")

def main():
    print("🚀 Roo Code (File Watcher) started...")
    print(f"Watching {INCOMING}...")
    
    while True:
        files = [f for f in os.listdir(INCOMING) if f.endswith(".json")]
        if files:
            for f in files:
                process_file(f)
        
        time.sleep(2)

if __name__ == "__main__":
    main()
